### ISSUE TITLE
[建议] 可以优化一下内存占用吗？

### ISSUE THREAD

**Issue by m1dor1** [gonelist/gonelist#23]
不到2万个文件，内存占用150+MB，可能是搜索的问题？

**Comment by cugxuan** [comment]
物理内存吗？
$ ps aux | grep gonelist
里面有两个值，右边那个是物理内存，我现在不到 150 个（文件+文件夹），内存大概是 20MB

**Comment by m1dor1** [comment]
是的，谢谢回复～

```
# ps aux | grep gonelist
root       567  0.3 20.3 892232 159796 ?       Sl   1月01   1:37 ./gonelist_linux_amd64
```

刚刚换回 v0.4.2：

```
# ps aux | grep gonelist
root      2939  1.8  6.9 753952 54980 pts/0    Sl   00:51   0:00 ./gonelist_linux_amd64
```

相差有点大，似乎真是全局搜索的问题……

**Comment by cugxuan** [comment]
> 159
OK，感谢反馈。接下来会考虑。

顺便排查下问题，理论上加入搜索不会多这么多内存的😭
可能是我太菜了。我找找看

**Comment by cugxuan** [comment]
> 是的，谢谢回复～
> 
> ```
> # ps aux | grep gonelist
> root       567  0.3 20.3 892232 159796 ?       Sl   1月01   1:37 ./gonelist_linux_amd64
> ```
> 
> 刚刚换回 v0.4.2：
> 
> ```
> # ps aux | grep gonelist
> root      2939  1.8  6.9 753952 54980 pts/0    Sl   00:51   0:00 ./gonelist_linux_amd64
> ```
> 
> 相差有点大，似乎真是全局搜索的问题……希望可以在配置文件里关闭全局搜索。

![image](https://user-images.githubusercontent.com/23120372/104261919-7c8d7a00-54c1-11eb-863d-d9c0248e6b5d.png)

我花了几天时间排查了一下，发现搜索功能增加的内存并不多。原来的 v0.4.2 也得要 160MB、
你看到的之前的内存是因为还没有刷新、因为借助 api，内存里面需要缓存两份文件目录、
