### ISSUE TITLE
Linux arm64版本

### ISSUE THREAD

**Issue by ChirmyRam** [gonelist/gonelist#24]
请问老哥release里面的Linux arm是64位版本吗？我有一台比较特殊的设备，可以运行cloudreve的Linux arm64版本，然而运行gonelist的Linux arm就提示illegal instruction。
可惜我不会编译，如果不是Linux arm64的话，下次发布可否再编译一个版本呢？|･ω･｀)
如果是Linux arm64的话，我就自认倒霉(´；ω；`)

**Comment by cugxuan** [comment]
@ChirmyRam 好的。已经在 v5.0 的 release 中加入了 linux_arm64 版本的包了。后续新版会加上、

**Comment by ChirmyRam** [comment]
> @ChirmyRam 好的。已经在 v5.0 的 release 中加入了 linux_arm64 版本的包了。后续新版会加上、

非常感谢(＾－＾)V
