### ISSUE TITLE
音乐播放模块被遮挡

### ISSUE THREAD

**Issue by ChirmyRam** [gonelist/gonelist#25]
如图，当音乐列表足够长的时候，音乐播放模块被音乐列表遮住，不方便操作。😑
![被遮挡](https://ae01.alicdn.com/kf/Ua62a8a78d2c148ddb185c4e4c33a7d6b0.jpg)
可以将它放在最前面吗？

另外我的read好像无法显示，这是我的readme：https://gl.chirmyram.top/d/README.md
![readme](https://ae01.alicdn.com/kf/U6b9f5997d8724dc4814d3d5108fab715f.jpg)

**Comment by cugxuan** [comment]
@ChirmyRam 第一个问题之后修复，不过下一版时间暂时还不知道。可能会出一个小版本修复 bug、
第二个问题，我测试了没有问题，可能需要查看一下日志，你的 arm 设备能够正常下载 README.md 么。、

**Comment by ChirmyRam** [comment]
> @ChirmyRam 第一个问题之后修复，不过下一版时间暂时还不知道。可能会出一个小版本修复 bug、
> 第二个问题，我测试了没有问题，我临时上传到了 https://gonelist.cugxuan.cn/#/test ，可能需要查看一下日志，你的 arm 设备能够正常下载 README.md 么。、

可能是我文件太多了吧，在云服务器上启动的时候都要卡很久😑

**Comment by cugxuan** [comment]
@ChirmyRam 强烈建议不要把刷新时间设置得太短，设置 20 分钟都挺好。我看你的 README 里面写的一分钟，没有这个必要，而且当前刷新机制设置成 1 分钟有 bug，我改了还没发新版、

**Comment by ChirmyRam** [comment]
> @ChirmyRam 强烈建议不要把刷新时间设置得太短，设置 20 分钟都挺好。我看你的 README 里面写的一分钟，没有这个必要，而且当前刷新机制设置成 1 分钟有一些不妥的地方（当前是按照每分钟开始，比如 1 分钟，2 分钟），我改了还没发新版、修改之后的逻辑是刷新完所有内容以后再等待一段时间再刷新。

啊这，好的吧

**Comment by cugxuan** [comment]
> > @ChirmyRam 强烈建议不要把刷新时间设置得太短，设置 20 分钟都挺好。我看你的 README 里面写的一分钟，没有这个必要，而且当前刷新机制设置成 1 分钟有一些不妥的地方（当前是按照每分钟开始，比如 1 分钟，2 分钟），我改了还没发新版、修改之后的逻辑是刷新完所有内容以后再等待一段时间再刷新。
> 
> 啊这，好的吧

缓存有效期是一个小时呢，设置太短也没啥用，除了更快刷新修改内容

**Comment by StringKe** [comment]
遮挡问题已经修复 https://github.com/gonelist/gonelist-web/commit/538190a81a71001b472fc1a0dbc1b16fb693ea16

**Comment by cugxuan** [comment]
今天 release 新版本即可用、

**Comment by ChirmyRam** [comment]
> 遮挡问题已经修复 [gonelist/gonelist-web@538190a](https://github.com/gonelist/gonelist-web/commit/538190a81a71001b472fc1a0dbc1b16fb693ea16)

非常感谢

**Comment by ChirmyRam** [comment]
> 今天 release 新版本即可用、

非常感谢。
