### ISSUE TITLE
[Feature] Multilingual support

### ISSUE THREAD

**Issue by adan89lion** [gonelist/gonelist#26]
Do you have plans to implement multiple languages? I am willing to contribute to English, Korean, French and Traditional Chinese translations.

**Comment by cugxuan** [comment]
Thanks!
I have never thought that my project would be used to the people in other countrys. I'm so glad there are someone to help me implement multiple languages.

I think the functions of this project have many points to improve. So I haven't write documents in English, and also I'm not so good at English.

I'm going to convert the configration file from `config.json` to  `config.yaml` in next version. Could you help me after several weeks?

In addition, how could I get in touch with you? By telegram or others?
At last, you are so kind! Good Luck!

**Comment by adan89lion** [comment]
Happy Lunar New Year!

Take your time, I am celebrating the New Year at home too😁!

I can start with the UI translations to English, Korean and French (I’m a French major), as well as to help translating the documentation (but it might need some effort).

You can contact me here at GitHub (because I am afraid of spam bots on Telegram or other messaging apps, they scan regularly for IDs).

**Comment by cugxuan** [comment]
I think I could translate the documents to English, and I's so glad that someone could help me to improve them.😇
The job of  UI translations need to waiting for @StringKe to refactor the web application. I will communicate with him and tell you what to do.
Thanks!

**Comment by cugxuan** [comment]
just close
