### ISSUE TITLE
希望官方可以出hub.docker.com的arm/arm64镜像

### ISSUE THREAD

**Issue by SoraKasvgano** [gonelist/gonelist#29]
希望官方可以出hub.docker.com的arm/arm64镜像
emmmm

**Comment by cugxuan** [comment]
OK，负责 Docker 这边的大佬说五一安排。

**Comment by SoraKasvgano** [comment]
> OK，负责 Docker 这边的大佬说五一安排。
az
大佬可否问一下支不支持E3 5T的那个business订阅

**Comment by cugxuan** [comment]
E3的5T有什么不同吗。跟普通的国际版的api地址不一样吗？

**Comment by SoraKasvgano** [comment]
> E3的5T有什么不同吗。跟普通的国际版的api地址不一样吗？

应该是一样的....群晖cloud sync 上的onedrive business可以登陆，个人的不行。。。

网页登陆进去是sharepoint的域名

**Comment by cugxuan** [comment]
抱歉，近期很忙，没办法支持了。
可能等一段时间、建议先找其他的替代品。😅

**Comment by SoraKasvgano** [comment]
> 抱歉，近期很忙，没办法支持了，我也不知道是不是替换一下api链接就好
> 可能等挺长一段时间、建议先找其他的替代品。😅

好耶

**Comment by zhangguanzhang** [comment]
五一我整下github action支持多架构镜像

**Comment by zhangguanzhang** [comment]
https://hub.docker.com/r/zhangguanzhang/gonelist/tags?page=1&ordering=last_updated
v0.5.2开始后有多架构镜像了
