### ISSUE TITLE
使用docker run运行出错emmm不知道哪里命令不对

### ISSUE THREAD

**Issue by SoraKasvgano** [gonelist/gonelist#31]
`docker run -d -p 8000:8000 --name gonelist --restart=unless-stopped -v /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro -v /home/gonelist/config/:/etc/config/ -e token_path=/etc/config/ -e CONF_PATH=/etc/config/config.json zhangguanzhang/gonelist:latest`

**Comment by SoraKasvgano** [comment]
日志为
`
time="2021-06-01 15:20:39" level=fatal msg="导入用户配置出现错误: invalid character 'r' looking for beginning of value",
time="2021-06-01 15:20:39" level=info msg="当前使用的配置文件为:/etc/config/config.json",
time="2021-06-01 15:20:13" level=fatal msg="导入用户配置出现错误: invalid character 'r' looking for beginning of value",
time="2021-06-01 15:20:13" level=info msg="当前使用的配置文件为:/etc/config/config.json",
time="2021-06-01 15:19:59" level=fatal msg="导入用户配置出现错误: invalid character 'r' looking for beginning of value"`

**Comment by zhangguanzhang** [comment]
`cat -A`看下配置文件，应该需要dos2unix下配置文件

**Comment by cugxuan** [comment]
`/etc/config/config.json` 出问题了，看一下配置文件内容、

**Comment by SoraKasvgano** [comment]
@cugxuan @zhangguanzhang 

`remote: onedrive

level: 2

client_id: 9710d4c4-e632-4608-11111
client_secret: a914b328-ebed-4589-11111


redirect_url: http://localhost:8000/auth

state: 23333
token_path:

download_redirect_prefix:

server:
  ReadTimeout: 0
  WriteTimeout: 0
  bind_global: true
  dist_path: ./dist/

  folder_sub: /
  gzip: true
  port: 8000

  refresh_time: 10
  site_url: http://localhost:8000
pass_list:
  - pass:
    path:
`

**Comment by cugxuan** [comment]
知道问题了。谢谢反馈。

**Comment by cugxuan** [comment]
docker 已经更新，需要重新 pull 镜像然后部署，使用最新的 docker-compose.yml
https://github.com/gonelist/gonelist/blob/master/docker-compose.yml

**Comment by SoraKasvgano** [comment]
> docker 已经更新，需要重新 pull 镜像然后部署，使用最新的 docker-compose.yml
> https://github.com/gonelist/gonelist/blob/master/docker-compose.yml
> 
> 现在的目录结构应该是
> 
> ```
> .
> ├── config
> │   └── config.yml
> └── docker-compose.yml
> ```

az

大佬可不可以docker run运行，arm架构 的compose 安装不打完整emmmmm

**Comment by cugxuan** [comment]
现在都是支持的呀，可以直接用 docker 也可以用 arm 架构的包。

**Comment by zhangguanzhang** [comment]
arm64的docker-compose的话下载地址 https://github.com/zhangguanzhang/docker-compose-aarch64
