### ISSUE TITLE
缓存刷新时无法正常使用，若文件很多，则对使用影响显著

### ISSUE THREAD

**Issue by zr1530052796** [gonelist/gonelist#34]
缓存刷新时无法正常使用，实测1分钟约刷新1万个文件。由于刷新间隔最大设置为60分钟（超过60分钟则刷新的链接失效），若存储海量文件，则不能使用的时间占比很明显，会影响正常的使用。如存储10万个文件，则每小时至少有1/6时间系统处于无响应状态。
请问是否可以避免这种情况？希望刷新过程中程序仍然保持正常响应。我看到release里面写到TODO优化缓存刷新方式，是否是针对这个问题？谢谢！

**Comment by cugxuan** [comment]
10W 个文件会一直没有响应，现在是全量刷新的方式，有计划修改为渐进刷新 URL 的方式、不过还在开发中。

**Comment by huoxue1** [comment]
你好，你的问题在最新v.0.5.5版本中初步已经得到了解决
