### ISSUE TITLE
[Question]部署完成之后所有文件下载请求都提示:10002 未找到对应项目

### ISSUE THREAD

**Issue by retroxz** [gonelist/gonelist#42]
onedrive版本: 国际版
gonelisrt版本: v0.5.5
linux版本: centos7
项目地址: https://record.retroxz.xyz/

部署完成后，可以正常加载列表，但无法进行文件下载。

```
// 20220402224809
// https://record.retroxz.xyz/d/EchoLive/%E5%89%AA%E8%BE%91%E7%89%87%E6%AE%B5-21641569-20200511-224914-%E3%80%90rabi-ribi%E3%80%91%E5%85%94%E5%A5%B3%E7%8B%BC%E5%B0%84%E5%B0%84%E5%B0%84.flv

{
  "code": 10002,
  "msg": "未找到对应项目"
}
```

**Comment by huoxue1** [comment]
麻烦查看一下后台有无报错日志

**Comment by huoxue1** [comment]
然后可以尝试一下，删除目录下的`.token .file_toen data.db`文件重新部署一下

**Comment by retroxz** [comment]
后台没发现报错日志 可能是我没开启debug模式的原因？我在文档中没找到开启debug模式的内容
现在的情况是这样的：
如果用release中的v0.5.5版本：文件下载和播放就是正常的
但是v0.5.5版本会出现folder_sub配置不生效的问题，网盘的起始目录会一直是onedrive的根目录
所以我参考了[#41 ](https://github.com/gonelist/gonelist/issues/41)中的方法，下载了[action](https://github.com/gonelist/gonelist/actions/runs/2077551341)中的版本
运行该版本后无法正常下载文件

**Comment by huoxue1** [comment]
好的。我去看下#41的提交哦
