### ISSUE TITLE
arm32 docker镜像

### ISSUE THREAD

**Issue by GreenHatHG** [gonelist/gonelist#44]
请问下能打包个支持arm32的docker镜像吗

**Comment by zhangguanzhang** [comment]
[gonelist_linux_arm.tar.gz](https://github.com/gonelist/gonelist/releases/download/v0.5.5/gonelist_linux_arm.tar.gz)
这个就是arm32的

**Comment by GreenHatHG** [comment]
请问这个是源码吗，得自己build一个docker镜像

**Comment by zhangguanzhang** [comment]
正在添加这个架构构建，稍后看下结果

**Comment by zhangguanzhang** [comment]
https://hub.docker.com/r/zhangguanzhang/gonelist/tags
已经有了，latest标签
